### ISSUE TITLE
Color customization across components

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/airship#127]
We need to address color customization between Airship components. We started a discussion in https://github.com/CartoDB/airship/pull/108#discussion_r207145091 but it's better to handle it here.

Right now, we are setting BEM modifiers such as `--primary`, `--secondary` and others to allow users customize the color styling in every component.

It is not bad, but we are repeating the same code over and over to achieve the same thing, and CSS classes such as `.as-container--primary` don't reflect what it modifies in the component.

So we need to debate the way to do it.

I proposed a component customization via attributes, like 
```html
<div class="as-container" color="primary"></div>
```

Or via CSS classes like: 
```html
<div class="as-container color-primary"></div>
```

Let's debate pros and cons!

**Comment by ivanmalagon** [comment]
This will be done using utility classes.
