### ISSUE TITLE
UI tests improvements

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/airship#148]
- [x] Remove old testing scripts
- [x] Clean `package.json` files
- [ ] Make backstop.js logs cleaner
- [x] Make tests stable waiting for the page to load instead using a delay

cc @ivanmalagon

**Comment by ivanmalagon** [comment]
Can we close this @IagoLast ? What did you mean with `make backstop.js logs cleaner`?

**Comment by IagoLast** [comment]
We can close it.

> What did you mean with make backstop.js logs cleaner?

Meh, I meant backstop logs lots of noise, but its ok
