### ISSUE TITLE
More colours for badges

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#151]
We've adopted semantic names for badges in https://github.com/CartoDB/airship/pull/147

In the design we have only 4 specific colours that we've named as `gray`, `green`, `blue` and `pink`.

![image](https://user-images.githubusercontent.com/1078228/43959108-fbcbf7e8-9cad-11e8-8d75-6d1be4319bad.png)

We need a broader palette of colours for badges with the same feel. @CartoDB/design

**Comment by urbanphes** [comment]
Another tag that It would be interesting:

Text: `#2E3C43`
Badge: `#F8E71C`

![slice](https://user-images.githubusercontent.com/14546701/43960723-2fcf6480-9cb3-11e8-9f2b-9981533e7c88.png)

**Comment by ivanmalagon** [comment]
Added in https://github.com/CartoDB/airship/pull/147
