### ISSUE TITLE
Refactor colors

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#154]
### Context
After a [brief discussion about badge colors](https://github.com/CartoDB/airship/pull/147#discussion_r209565796) and checking with @urbanphes we realized that mentioned table colors are not specific to tables. They are based on the global colors.

Examples:

![image](https://user-images.githubusercontent.com/1078228/44033992-54f8b9c2-9f0c-11e8-89ef-8d8f2b1743b7.png)

In the dropdown, the font color if the primary color, the hover color is the complementary one with 16% of opacity

![image](https://user-images.githubusercontent.com/1078228/44034119-a1ea7536-9f0c-11e8-9799-6bc07545a284.png)

In tabs, text uses the primary color, the bar uses UI 03 and the selected bar is the complementary color.

![image](https://user-images.githubusercontent.com/1078228/44034169-c086418c-9f0c-11e8-954d-ea3aceb5e744.png)

In tables, the same. Header is UI 03, hover is complementary with 16% of alpha and the selected cell is 32% of alpha.

The goal of all this is that if we customize the colors from the palette, everything will behave.

This issue is to check if we are following this path. If not, we should refactor the CSS to take this into account.

**Comment by IagoLast** [comment]
i´d add those new colours to our list

**Comment by IagoLast** [comment]
So my proposal:

1. Add a new `support` color `as-color-support-04` (#E2E6E3)
2. Use custom ad-hoc green colors for tables and the remaining elements

**Comment by ivanmalagon** [comment]
1. That color is already `--as-color-ui-03`. No need to add a new one.
2. Tables and elements should use `--as-color-complementary` but with alpha in some cases. Check https://stackoverflow.com/questions/40010597/how-do-i-apply-opacity-to-a-css-color-variable

**Comment by IagoLast** [comment]
umm, but can we use rgba + css variables + css variables fallback?

**Comment by ivanmalagon** [comment]
Don't know bout the fallback but in that thread they write an example of CSS variables + alpha

**Comment by IagoLast** [comment]
```css
background: var(--as-color-ui-03, fallback);
```

does this work?

```css
background: var(rgba(--as-color-ui-03), rgba(fallback));
```

**Comment by ivanmalagon** [comment]
We refactored the naming color guideline in https://github.com/CartoDB/airship/pull/470

In case we need to address some changes to styling due to new issues, they'll be addressed in new tickets.
