### ISSUE TITLE
Add dependencies on the documentation of airship

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/airship#17]
We would need to indicate in the documentation the dependencies **prop-types** and **styled-components**, due to npm is not downloading them when downloading airship through the next command and this might lead to confusion when setting up the environment.

```bash
npm install --save @carto/airship
```

cc @rubenmoya  @piensaenpixel

**Comment by rubenmoya** [comment]
Added to the README and the documentation, thank you!
