### ISSUE TITLE
Range slider text shouldn't move when hovering

### ISSUE THREAD

**Issue by rubenmoya** [CartoDB/airship#171]
### Context
The text in the range slider shouldn't move when hovering or dragging.

![range-slider-text](https://user-images.githubusercontent.com/905225/44411383-a8ada680-a566-11e8-9d29-bed1b2fbb323.gif)

### Steps to Reproduce
1. Create a range slider
2. Hover in a thumb

### Current Result
The text moves

### Expected result
The text doesn't move

**Comment by jesusbotella** [comment]
That behaviour was done on purpose. If the text doesn't slide down, you are not able to see what value the slider is at. I wouldn't consider this a bug.

**Comment by jesusbotella** [comment]
I was wrong! Merged :)
