### ISSUE TITLE
Publish in our own CDN

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#173]
Airship CSS is used in the examples using jsdelivr. It has an aggressive cache mechanism so a new published version is not available until 24h has passed.

Add our own CDN `https://libs.cartocdn.com/` to our release process for the three packages: components, icons, style.

**Comment by jimaek** [comment]
Hey, jsDelivr offers an easy to use cache purge API to deploy new versions. You can use it during your deployments and completely automate the process

```
CDN URL:
https://cdn.jsdelivr.net/npm/jquery@3.2.1/AUTHORS.txt

Purge URL:
https://purge.jsdelivr.net/npm/jquery@3.2.1/AUTHORS.txt


Multiple files (20 limit):

curl -X POST \
  http://purge.jsdelivr.net/ \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -d '{
	"path": [
		"/npm/test",
		"/npm/test2",
		"/npm/test3"
	]
}'
```
