### ISSUE TITLE
Grid component does not allow change the CSS Grid parameters

### ISSUE THREAD

**Issue by oriolbx** [CartoDB/airship#18]
According to the code defined [here](https://github.com/CartoDB/airship/blob/master/src/components/Grid/grid.js)

The width of the grid has 1 static value and can't be use to change the parameters of the CSS Grid like grid-template-columns, this constraints a lot the usage of the Grid component, due to it is not possible to make the Grid responsive or customize the Grid in further ways

cc @rubenmoya @piensaenpixel

**Comment by rubenmoya** [comment]
To be honest, this component doesn't make any sense to me, you'll need to match 1 to 1 every CSS property to a component property... so at the end, it's easier to write your own CSS...

**Comment by rubenmoya** [comment]
Closing since we removed the `Grid` component
