### ISSUE TITLE
Range component implementation on a legend

### ISSUE THREAD

**Issue by rafaelfernandezgis** [CartoDB/airship#20]
Hi there, I'm trying to implement the Range airship component into a legend to change a layer transparency value. Also I'm using the 'react-leaflet-control' extension to render components in the map container.
The problem is I can see the Range component, but I can't drag the slider. I suspect it's because of the mouse over Propagation 'react-leaflet-control' has already implement.

If I put the Range component on a regular DIV (without 'react-leaflet-control') then I can drag both, slider and map, as a block In this specific case, I'd need to disable the propagation.

Can you please take a look at this behavior? Maybe by using props to enable or disable propagation would be great.

Thx!

**Comment by rubenmoya** [comment]
Hi!

This should be fixed using the `1.0.0-alpha.22` version.

Here is a small example reproducing your error: https://codesandbox.io/s/88nvr91mxl if you want to check it out.

Let me know if it works for you to close the issue :)

**Comment by rafaelfernandezgis** [comment]
That's perfect Ruben, works like a champ!
Thanks a lot,

Rafael Fernández
