### ISSUE TITLE
Range component value does not update when state changes (no synch between state and value)

### ISSUE THREAD

**Issue by rafaelfernandezgis** [CartoDB/airship#21]
Hi there,
I believe there is a lack of synchronization between the state and the value in the AirShip Range component. For a better comprehension of the problem, I modified this [codesandbox](https://codesandbox.io/s/4x09p1lv20). So I put a button close Range div, any time you click, the state changes and then the text and the zoom level update properly however the Range keeps invariable.

![capture](https://user-images.githubusercontent.com/6051197/39307762-fb8c3402-4963-11e8-94f8-4ae398f48738.PNG)

Any thoughts?
Rafael

**Comment by rubenmoya** [comment]
Thank you for reporting it! You are totally right, the component wasn't updating accordingly when receiving new props it should be fixed in `1.0.0-alpha.23`
