### ISSUE TITLE
Color ranges in histogram

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#218]
### Context
We couldn't add one the planned props to the histogram widget in the first cycle.

**Color range**
The color range to apply to the bars. Useful when combined with style metadata. Format:
```
[
  {
    "min": 9,
    "max": 20,
    "value": "#7F3C8D"
  },
  {
    "min": 20,
    "max": 25,
    "value": "#11A579"
  },
 ...
]
```

Note that this metadata could not coincide with the data buckets so an interpolation will be needed (just as it happens in Builder)

The effect on the histogram should reflect the same behaviour as autostyle in Builder.

![image](https://user-images.githubusercontent.com/1078228/44853470-5c4d1f80-ac66-11e8-8e90-655bc8d89ce1.png)

**Comment by ivanmalagon** [comment]
The use case:

Someone has a ramp applied to a number column, for instance, price. The data is aggregated in 7 buckets.

![image](https://user-images.githubusercontent.com/1078228/47287644-42d7ac80-d5f3-11e8-9021-7e9cf1178691.png)

The user wants to add an histogram to see the distribution of the data. She wants a detailed one so she sets 24 buckets.

![image](https://user-images.githubusercontent.com/1078228/47287759-a530ad00-d5f3-11e8-94df-4ea6a0f6efc3.png)

Now, the user want to relate what she is seeing in the map with the data in the histogram.

![image](https://user-images.githubusercontent.com/1078228/47287809-ca252000-d5f3-11e8-82fe-2bbb7d562cc2.png)

As you can see, the bucket range in the histogram doesn't have to coincide with the ramps ranges. So we need to do an internal mapping to provide right gradients in each rect.

The way the user provides the range it's up to her: it could be coming from CARTO.js, CARTO VL or a random decision. The widget must provide a property to set that color ranges and that's it.

**Comment by IagoLast** [comment]
Thx for the explanation Ivan! Now it's clear to me 😄 

The API with CARTO.js is immediate because they are just the metadata. We have to check the CARTO-VL compatibility. 

The use case does not make much sense from the point of view of product or UX.

I think that mixing a quantified variable in two ways in one visualization is confusing! Why would someone want to do that? If you do not know the horizontal color scale does not provide any extra information. Is there a case in which this adds value?


(cc @davidmanzanares)

**Comment by IagoLast** [comment]
update after a quick meeting:

- This is a feature available in builder that some customers want
- The feature is incorrect from a formal point of view
  - A legend should be used instead

**Comment by ivanmalagon** [comment]
After a talk with @rochoa, @davidmanzanares and @IagoLast let's keep it simple.

Instead of making an assumption of linearity in the color distribution, let's allow the user to set a solid color for each bucket if they want to.

```
  histogramWidget.data = [
    { start: 0, end: 10, value: 5, color: #FABADA },
    { start: 10, end: 20, value: 10, color: #C0FFEE },
    { start: 20, end: 30, value: 15 },
    { start: 30, end: 40, value: 20 },
    { start: 40, end: 50, value: 30 },
  ];
```

This way, the logic behind filling the buckets it's totally up to the user, it's simpler for us and consistent with the Category widget. It gives freedom but we don't make any assumption for the user.
