### ISSUE TITLE
Gauge chart over title and description on IE11

### ISSUE THREAD

**Issue by arkaitz97** [CartoDB/airship#22]
### Context
*Please explain here below what you were doing when the issue happened*
I was reading the documentation in IE11.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Open IE11
2. Go to https://carto-airship.netlify.com/#/components/gaugechart

### Current Result
*Please describe here below the current result you got*
Gauge chart is over the title and description
![image](https://user-images.githubusercontent.com/21361471/39562645-14433ef2-4ead-11e8-8a1b-d469dfc5d002.png)

### Expected result
*Please describe here below what should be the expected behaviour*
Gauge chart should be at the bottom right of title and description
![image](https://user-images.githubusercontent.com/21361471/39562653-2986a682-4ead-11e8-99c5-2ada0f8061de.png)

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*
IE11

### Additional info
*Please add any information of interest here below*

**Comment by ivanmalagon** [comment]
We're changing the approach of Airship. After gathering feedback from several partners and users, we are recoding the widgets as Web Components and providing a CSS framework for layout and simple components. In our tests this has been easily integrated with React, Angular or vanilla and will help us to broaden our partners support. A React components-only library has not worked as well as we thought initially.

That means that the current Airship repository is stale and no further development on React is expected. Feel free to fork the current project and make whatever change you need in case you need the widgets as React components.

I'm marking this issue as frozen to check that it doesn't happen once we port the Gauge chart to Web Components.

Sorry for the inconveniences and thanks for your feedback.
