### ISSUE TITLE
Improve CDN version management

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/airship#220]
Currently, we can only point to a specific version of Airship through our CDN:

```
https://libs.cartocdn.com/airship-components/v1.0.0-alpha.37/airship.js
```

The idea is update our cdn scripts to reach the following:

- By default point to the latest stable version
- Allow to download an specific version
- [optional] When pointing to a incomplete version, redirect to the latest (cdn://airship-2 --> cdn://airship-2.1.7)

@Jesus89  You did something similar in carto-vl right? 

cc @jesusbotella

**Comment by Jesus89** [comment]
Yes, we have a script (not a task) to do that: https://github.com/CartoDB/carto-vl/blob/master/scripts/cdn/publish.js

For example, a stable release is published as `vA`, `vA.B` and `vA.B.C`. And a pre-release as `vA.B.C-D` and `vA.B.C-D.E`. Just use different directories for each option.

```
v1.2.3: v1 / v1.2 / v1.2.3
v1.2.3-beta.4: v1.2.3-beta / v1.2.3-beta.4
```
