### ISSUE TITLE
First integration of Airship into the Developer Center

### ISSUE THREAD

**Issue by inigomedina** [CartoDB/airship#224]
The public release of Airship requires a proper integration into the Developer Center (DC). It is a really important aspect of Airship as a product since it will be mainly consumed through the DC. That is, Airship will be what the DC conveys it is.

The first step of that integration means three main things:

- [x] Set up Airship as a component of the DC: its position, along with the rest of the components, on the homepage, landing, etc.
- [x] Set up the architecture of contents the first public release will include.
- [ ] Create its branding pattern: icon and color.

**Comment by inigomedina** [comment]
@IagoLast, as the first step of the integration I need to set up some basic things (folders, etc.) as the common structure that the Developer Center waits for any component.

Everything ok if I create a new branch to work on these things? We would use this branch as the main reference for the DC integration.

**Comment by IagoLast** [comment]
sure, paste the branch name here once you have it

**Comment by inigomedina** [comment]
`developer-center` is the branch we will use as the main reference for the Developer Center integration. I'll start putting contents in there, as the beginning just to replicate the structure we want.

**Comment by inigomedina** [comment]
Hey @piensaenpixel, we already have the first basic integration of Airship into the Developer Center. You can take a look at staging: http://airship-integration.developers.carto-staging.com/developers/

As you can see above, one of the points we created as part of this first integration is related to the branding side of the component. 

Do you think you might help with that?

**Comment by IagoLast** [comment]
Closing this issue Since remaining work is design
