### ISSUE TITLE
Loading element's animation isn't working on IE11

### ISSUE THREAD

**Issue by arkaitz97** [CartoDB/airship#23]
### Context
*Please explain here below what you were doing when the issue happened*
I was reading the documentation in IE11.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Open IE11
2. Go to https://carto-airship.netlify.com/#/components/loading

### Current Result
*Please describe here below the current result you got*
Loader isn't doing the animation
![image](https://user-images.githubusercontent.com/21361471/39562756-b4f52ba8-4ead-11e8-8035-3b80338a2713.png)

### Expected result
*Please describe here below what should be the expected behaviour*
Loader should be spinning
![image](https://user-images.githubusercontent.com/21361471/39562752-ad9199fa-4ead-11e8-9f18-69e66319be5b.png)

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*
IE11

### Additional info
*Please add any information of interest here below*

**Comment by IagoLast** [comment]
This Airship version has been deprecated
