### ISSUE TITLE
Guides: Layout

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/airship#236]
Create a guide explaining the basics of the airship layout

- Overview
- Grid system
- Responsive breakpoints
- Examples
- Link to templates

**Comment by jesusbotella** [comment]
We need to **clearly** state that if you use `<as-application-container>` you need to put Mapbox.GL/Leaflet code inside `load` event. Well, not only Mapbox.GL/Leaflet but all layout-dependant code.
