### ISSUE TITLE
Radio button has multiple circles inside it on IE11

### ISSUE THREAD

**Issue by arkaitz97** [CartoDB/airship#24]
### Context
*Please explain here below what you were doing when the issue happened*
I was reading the documentation in IE11.

### Steps to Reproduce
*Please break down here below all the needed steps to reproduce the issue*

1. Open IE11
2. Go to https://carto-airship.netlify.com/#/components/radiobutton

### Current Result
*Please describe here below the current result you got*
IE11 shows up multiple circles on the selected radio button
![image](https://user-images.githubusercontent.com/21361471/39562971-9485bc10-4eae-11e8-8033-cdec3d6d8c7e.png)

### Expected result
*Please describe here below what should be the expected behaviour*
It should be showing a single circle inside the selected radio button
![image](https://user-images.githubusercontent.com/21361471/39562957-897e918e-4eae-11e8-9420-a566f2b742fd.png)

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*
IE11

### Additional info
*Please add any information of interest here below*

**Comment by IagoLast** [comment]
This Airship version has been deprecated
