### ISSUE TITLE
Issues when airship layout slightly different

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/airship#247]
While writing a Vue app we had to add a `<div>` to wrap several components together. 

The markup looks more or less like:

Parent element:
```html
<main class="as-app-content">
    <custom-component >
</main>
```

custom-component:
```html
<template>
  <div> <!-- this div is mandatory -->
    <irrelevant-component />
    <aside class="as-sidebar as-sidebar--l as-sidebar--right">...</aside>
  </div>
</template>
```

The issue is that the `as-sidebar` is not a direct child of the `as-app-content`, which is the intended use. That div has neither `flex: 1` nor `display: flex`, but adding them explicitly will solve the issue.

This issue is a request to consider if this is intended, should be fixed somehow, whether we should consider it important enough to document it, etc etc

**Comment by IagoLast** [comment]
Maybe is a stupid question but why you cant do:

```html
<template>
    <aside class="as-sidebar as-sidebar--l as-sidebar--right">...</aside>
</template>
```

??

**Comment by jesusbotella** [comment]
Yes, this problematic is hard to solve.

Given that `.as-app-content` is a layout class, I couldn't come up with a solution other than the ones you put in issue content. It is a limitation of the layout rendering :(

**Comment by IagoLast** [comment]
Regarding to this, we are going to remark in the [layout guides](https://github.com/CartoDB/airship/issues/236) that users should follow the predefined layout format.

in any case cc @ivanmalagon before closing this. :)
