### ISSUE TITLE
Toolbar anchor color

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/airship#248]
When adding a toolbar with some `<a>` elements, the icon & text color is the complementary.

![image](https://user-images.githubusercontent.com/446970/45090657-3ca77280-b110-11e8-8473-565e63a714ad.png)

Not sure if it's intended behaviour or not, but it looked fairly weird.

I've located the issue on _toolbar.scss:27

There's a CSS variable so it's easy to overwrite only for the toolbar.

**Comment by jesusbotella** [comment]
The change was introduced [here](https://github.com/CartoDB/airship/commit/585ac2b0448b2b2b9a447b6b5a87e1fec83d35c7#diff-e9307645e9af6f13bd521f3c98c5c347R27) but I don't think it was intended. I saw it in sketch and they use `color-ui-01`.
