### ISSUE TITLE
Histogram component to contain only numeric data

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#25]
### Context

Our current histogram implementation is in reality a Bar chart. Histograms are a representation of the distribution of numerical data.

To reflect its authentic nature we need to make several changes:

#### Input data

Histogram component need to accept as data an array of buckets with this info:

```
data: [{
  start: number, // The lower limit of the bin
  end: number, // The upper limit of the bin
  value: number // To value represented in the bin
}]
```

The validations to do are to check that everything is a number.

#### X axis

Initial feedback is telling us that people want to see the X axis values. Taking a similar one designed in Airship sketch as an example.

![image](https://user-images.githubusercontent.com/1078228/39756936-89392916-52cb-11e8-9570-92fb3b2edbdf.png)

From that design, I assume that there's no vertical lines in Airship design.

Are you ok with this, @urbanphes ? Drawing x axis values and not showing vertical lines. If not, can you provide us with an example?

#### Documentation

Update documentation

#### Extra ball: bar chart

Since we're getting rid of the histogram component as a bar chart, can we use the current StackedBar as a replacement, @rubenmoya ?

I mean, using it with only one category would behave as the current histogram, right? If so, we can create a component called Bar chart and extend it to Stacked Bar chart.

**Comment by rubenmoya** [comment]
To be honest, I don't know, we should talk about what data formatting we want to use in the `StackedBar` component and maybe we can reuse it. The implementation is quite different from one to another because of the multiple bars.
