### ISSUE TITLE
Versioning and NPM publish

### ISSUE THREAD

**Issue by rochoa** [CartoDB/airship#267]
I don't know if it's already too late for this. Could we use a different versioning for the current releases until we have a 1.0.0 version? I mean, right now we are using a `1.0.0-{tag}-{revision}`, e.g. `1.0.0-alpha.27`.

We've had a couple of issues already with this approach: https://github.com/CartoDB/airship/issues/177 and https://github.com/CartoDB/airship/issues/245. Each time something like this happen, we need to contact NPM support via email because they have to remove the package themselves.

Furthermore, we won't be able to reuse any version we already published. E.g., we won't be able to publish `carto/airship-style@1.0.0` because we published it but asked NPM to unpublish it.

**Comment by rochoa** [comment]
No.

> Registry data is immutable, meaning once published, a package cannot change. We do this for reasons of security and stability of the users who depend on those packages. **So if you've ever published a package called "bob" at version 1.1.0, no other package can ever be published with that name at that version. This is true even if that package is unpublished.** However, because accidents happen we've allowed a 72 hour window for users to unpublish packages they have just created. Beyond that, unless in extreme cases, we'll prefer a deprecation path.

**Comment by IagoLast** [comment]
So according to this our first release should be the `2.0.0` right?

**Comment by IagoLast** [comment]
@rochoa 

Although we have two issues, it is an error that only happened once and it is unlikely to happen again unless someone publishes an incorrect version by mistake and in 72h no one notices. Plus we are using [lerna publish](https://github.com/lerna/lerna/tree/master/commands/publish) to release new versions, this tool has a nice CLI that makes hard to publish a wrong version so I think we are safe now.

In any case, I do not know how to use a different versioning system will help us.

**Comment by rochoa** [comment]
If you follow Semantic Versioning, using 0.MINOR.PATCH for initial development prevents these problems with version 1.0.0. Not talking about that being the recommended approach.

I guess that anyone forgetting about adding `--canary --preid alpha` will publish again a 1.0.0 version.

We can still use `1.0.1` as the first public release. 😂

**Comment by jesusbotella** [comment]
I told @IagoLast about `1.0.1`, I think I almost convinced him 😂

**Comment by IagoLast** [comment]
Ok so our first release will be `1.0.1`

**Comment by ivanmalagon** [comment]
`1.0.1` is still `1.0`
