### ISSUE TITLE
widget scroll issues

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/airship#269]
As seen in the following image we got no scroll when a widget has many elements.

We can fix this adding a scroll and a max-height to the widget itself or adding scroll to the sidebar.

[![Image from Gyazo](https://i.gyazo.com/be9337b073ab5800211992e8a4961863.gif)](https://gyazo.com/be9337b073ab5800211992e8a4961863)

**Comment by jesusbotella** [comment]
I think we should make sidebar scrollable when content overflows by default.

**Comment by IagoLast** [comment]
+1
