### ISSUE TITLE
Generate minified versions for style elements

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/airship#270]
Meanwhile StencilJS generates a minified version for component scripts, we are not generating it for styles. We should generate one minified version for the whole bundle, and same for all the mini-bundles containing each component styles.

**Comment by IagoLast** [comment]
Im going to use [node-sass](https://github.com/sass/node-sass#usage-1) with the `compressed` output function.

My current plan:

1) Compile the sass with the minify option
2) Use a script to rename the .css files to .min.css
3) Compile again but with the regular configuration


cc @jesusbotella @rjimenezda

**Comment by rjimenezda** [comment]
There's an open issue with source maps and outputStyle `compressed`. I don't particularly care for source maps on css, just a note.

Given that it's multiple steps, a shell script is probably easier than writing a complex one-line like `node-sass <whatever> && sed rename_all_css_to_min.css && node-sass <whatever2>`

**Comment by jesusbotella** [comment]
I wouldn't provide sourcemaps for minified CSS
