### ISSUE TITLE
[DISCUSSION] Utilities.

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#274]
### Context
There's an ongoing feeling on the Airship squad about utilities. For some of us there's no clear usage for them, for some others it's a great tool to have under our belt.

Main concerns:
- There are a lot of CSS only for them.
- Flex classes feels unnecessary.

Let's debate here and review the utilities generated CSS to address those concerns.

**Comment by IagoLast** [comment]
Our current `utilities.min.css` file takes 13.81KB (All Airship.css is 40.41KB)

We got the following [utilities](https://github.com/CartoDB/airship/tree/master/packages/styles/src/utilities)

- display
- text
- flex
- positioning
- spacing
- colors

IMO we should keep `colors` and `spacing` but reducing them to a subset of commonly used sizes

cc @ivanmalagon @jesusbotella

**Comment by jesusbotella** [comment]
Wow, I didn't expected it to weigh that much. I would do that too, just the common 8px multiples (grid size).
