### ISSUE TITLE
Examples using Airship in angular 5

### ISSUE THREAD

**Issue by dersteppenwolf** [CartoDB/airship#29]
Hi.
Is there some "quick start" example integrating Airship and angular 5?

**Comment by ivanmalagon** [comment]
Hola Juan Carlos.

We're changing the approach of Airship. After gathering feedback from several partners and users, we are recoding the widgets as Web Components and providing a CSS framework for layout and simple components. In our tests this has been easily integrated with React, Angular or vanilla and will help us to broaden our partners support. A React components-only library has not worked as well as we thought initially.

That means that the current Airship repository is stale and no further development on React is expected. Feel free to fork the current project and make whatever change you need in case you need the widgets as React components.

We'll provide guides for integrating the web components in Angular. They get along very well (https://custom-elements-everywhere.com/libraries/angular/results/results.html)

**Comment by dersteppenwolf** [comment]
... Stepping down the react hype...
