### ISSUE TITLE
Panels are not scrollable

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/airship#292]
Our panels-wrapper covers the full map, so to preserve the interactivity we got the [pointer events](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events) disabled.

This prevents the panels to have any kind of scroll.

**Comment by jesusbotella** [comment]
That's not accurate. While `.as-panels` has `pointer-events` set to none, `.as-panel__element` has `pointer-events` set to auto.

I suspect that the panel is not scrollable because it doesn't have `max-height` and `overflow: scroll`. But that's not Airship matter IMHO 🤷‍♂️
