### ISSUE TITLE
Modify airship theme

### ISSUE THREAD

**Issue by RominaMartin** [CartoDB/airship#31]
I'm currently using Airship with React and I'd like to know if there's a way to modify the theme colors.

I'm using Range component and I'd like to have it in another color but I'm not sure how to modify the theme since I only have the dist directory.

**Comment by ivanmalagon** [comment]
We're changing the approach of Airship. After gathering feedback from several partners and users, we are recoding the widgets as Web Components and providing a CSS framework for layout and simple components. In our tests this has been easily integrated with React, Angular or vanilla and will help us to broaden our partners support. A React components-only library has not worked as well as we thought initially.

That means that the current Airship repository is stale and no further development on React is expected. Feel free to fork the current project and make whatever change you need in case you need the widgets as React components.

Anyway, you can modify the theme colors on the file `theme.js`. In the current implementation, it's not possible to change the theme colors in real-time. You can fork the repo, and build a custom distribution with your modified colors.

Sorry for the inconveniences.
