### ISSUE TITLE
Range slider does not allow decimals

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#315]
### Context

Setting a slider for opacity like this:

```
            <as-range-slider
              id="opacity-slider"
              min-value="0"
              max-value="1"
              step="0.1"
              value="0.5"></as-range-slider>
```

### Result

![opacity](https://user-images.githubusercontent.com/1078228/45831710-5e078180-bd00-11e8-84a1-ee66060be00d.gif)

### Expected result
Values are rounded depending on the min and max value. In this case, we should see `0.1 0.2 0.3 ...`

**Comment by jesusbotella** [comment]
Gonna take a look at it along with #312 ;)
