### ISSUE TITLE
Dropdown not working

### ISSUE THREAD

**Issue by KarinaDavtyan** [CartoDB/airship#32]
### Context
I've implemented dropdown in the same they as it was presented in example but it's not working

### Steps to Reproduce

1. create-react-app
2.
 ```
<Dropdown
  action="over"
>
  <Dropdown.Trigger>
    <Button borderless>
      Hover me&nbsp;
    </Button>
  </Dropdown.Trigger>
  <Dropdown.Content>
    <Dropdown.Menu>
       <Dropdown.Item>Image</Dropdown.Item>
       <Dropdown.Item>Video</Dropdown.Item>
       <Dropdown.Item>None</Dropdown.Item>
    </Dropdown.Menu>
  </Dropdown.Content>
</Dropdown>
```
3.

### Current Result
*Please describe here below the current result you got*
Element is rendered but not reacting to any events

### Browser and version
*What internet browser (Chrome, Firefox, etc) and version was you using and version*
Chrome
"@carto/airship": "^1.0.0-alpha.25"

### Additional info
Button and RadioButton are working

**Comment by KarinaDavtyan** [comment]
It was actually an issue with z-index of Dropdown.Content not events
And I am trying to solve it but all tests for Tooltip component are failing with
```TypeError: Cannot read property '_ownerDocument' of undefined```

**Comment by ivanmalagon** [comment]
We're changing the approach of Airship. After gathering feedback from several partners and users, we are recoding the widgets as Web Components and providing a CSS framework for layout and simple components. In our tests this has been easily integrated with React, Angular or vanilla and will help us to broaden our partners support. A React components-only library has not worked as well as we thought initially.

That means that the current Airship repository is stale and no further development on React is expected. Feel free to fork the current project and make whatever change you need in case you need the widgets as React components.

Sorry for the inconveniences.
