### ISSUE TITLE
iFrames should point to a real example

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#333]
Responsive specimens in the reference are very useful to get a sense of what the style looks like. The problem is that you cannot access its code. I've found myself several times inspect the element to get the iframe URL and in a user testing, the user wanted to see the code with no success.

Below each iframe we have to add a link to a real example where the user can inspect the code. It can be not the exact map but a related one. For instance, in the floating panels section we could link to a real example with floating panels (even if it's not the same file, at least the user can copy&paste a working example).

**Comment by IagoLast** [comment]
Lets wait for https://github.com/CartoDB/airship/pull/360 to be merged and then we can add links
