### ISSUE TITLE
Layout schema in guides section is broken

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#334]
![image](https://user-images.githubusercontent.com/1078228/46020960-d8107f80-c0df-11e8-98ea-d5f06d25c85e.png)

The section should include a link to the Layout reference, not only a mention.

**Comment by IagoLast** [comment]
Solved in https://github.com/CartoDB/airship/commit/7ec050f5b05e4d1dd216e6bb4e8806b47794f48e

(accidentally pushed to master) 🙄
