### ISSUE TITLE
Layout containers definition

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#34]
For Airship v1.0, we aim to provide common layouts for LI apps. The goal of this issue is to define what containers should be included in the v1.0 release and its behaviour.

- [x] Toolbar [https://github.com/CartoDB/airship/issues/47](https://github.com/CartoDB/airship/issues/47)
- [x] Sidebar [https://github.com/CartoDB/airship/issues/49](https://github.com/CartoDB/airship/issues/49)
- [x] Bottom bar [https://github.com/CartoDB/airship/issues/56](https://github.com/CartoDB/airship/issues/56)
- [x] Floating containers [https://github.com/CartoDB/airship/issues/60](https://github.com/CartoDB/airship/issues/60)
- [x] Infowindow #78

**Comment by piensaenpixel** [comment]
Take a look @ivanmalagon, ping me if you missed anything

## Mobile views

# Sidebar
![image](https://user-images.githubusercontent.com/1214201/42553351-d7e786d8-84e0-11e8-9ae6-d9ed230d5e2e.png)
![image](https://user-images.githubusercontent.com/1214201/42553357-dc0a30f8-84e0-11e8-9f5f-dcac0d2010bf.png)
![image](https://user-images.githubusercontent.com/1214201/42553366-e7fa4bd2-84e0-11e8-8ed0-820504857702.png)
![image](https://user-images.githubusercontent.com/1214201/42553368-eafa0516-84e0-11e8-9230-25b257e2e821.png)



# Floating containers
![image](https://user-images.githubusercontent.com/1214201/42553364-e46397f8-84e0-11e8-8108-0ea1804874e2.png)

**Comment by ivanmalagon** [comment]
Summoning @CartoDB/design 

What breakpoints do you suggest for Airship?

Taking Hangar as an example
```scss
// Layout
$layout-tablet: 800px;
$layout-mobile: 600px;
$layout-regular: 980px;
```

Do you think these three apply to CARTOSolutions as well?

**Comment by kukukaka** [comment]
I guess we can adjust some pixels the breakpoints, but it's ok if we keep the same we are using right now for Hangar.

Maybe a bigger one in the future would makes sense, but I think that with he current layouts you shared only the sidebards would benefit from it, so probably not worth it. 

Also, I've one question. Are we providing only double sidebars layouts? No single?

Sharing for reference:

The Standard Bootstrap 4.x Breakpoints
@media all and (max-width: 1199px) { ... } 
@media all and (max-width: 991px) { ... } 
@media all and (max-width: 768px) { ... } 
@media all and (max-width: 575px) { ... }
 
e) The Material Design Lite (MDL) Breakpoints 

@media all and (max-width: 1024px) { ... } 
@media all and (max-width: 839px) { ... } 
@media all and (max-width: 480px) { ... }

**Comment by ivanmalagon** [comment]
After checking real layouts in detail I'm going to simplify our sidebar offering. The thin sidebar [will be a toolbar](https://github.com/CartoDB/airship/issues/47) and then we have our [regular sidebar.](https://github.com/CartoDB/airship/issues/49)

This answers every layout we've collected and simplifies a lot the logic.

**Comment by ivanmalagon** [comment]
Infowindow is pending.
