### ISSUE TITLE
Scroll is not working in reference

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#374]
In reference left menu, when there are a lot of content, the scroll doesn't work. You need to scroll the main content to be able to access the bottom of the menu.

I don't know if it's an easy fix. If not, perhaps we need to do our own Catalog fork to customize that menu.

Not urgent.

**Comment by IagoLast** [comment]
This is not going to be an easy-fix because we depend on the global developer-center layout.

Blocking this, pending discussion
