### ISSUE TITLE
Style framework guidelines

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#38]
For building the Airship CSS framework, these are the guidelines to follow:

- Sass preprocessor.
- BEM methodology.
- Namespacing: for utilities, state classes and JS hooks.
- ITCSS architecture.
- Stylelint.

These are common choices in CARTO.

- Sass preprocessor: used in Builder and Hangar.
- BEM methodology: we've tried to follow it but we are not consistent. Let's do it better this time. You can see it being used in [Hangar](https://github.com/CartoDB/hangar-alpha/blob/master/src/scss/components/_navbar.scss)
- Namespacing for utilities: used in Builder and Hangar. For instance, for positioning we use `.u-tspace-8` and `is-small`, `is-caption` for state. 
- ITCSS: suggested by @elenatorro Let's give it a try.
- Stylelint: used in Builder CI.

### Links

**BEM**
- [BEM introduction](http://getbem.com/introduction/)
- [BEM by example](https://seesparkbox.com/foundry/bem_by_example)
- [BEM 10 common problems](https://www.smashingmagazine.com/2016/06/battling-bem-extended-edition-common-problems-and-how-to-avoid-them/)

**Namespacing**
- [Writing modular CSS - namespaces](https://zellwk.com/blog/css-architecture-2/) Utilities and state applies.

**ITCSS**
- [Building a maintainable and scalable CSS with ITCSS](https://medium.okgrow.com/building-a-maintainable-and-scalable-css-codebase-with-itcss-ceda5b2f495b)
- [CSS at Trivago](https://medium.com/@pistenprinz/css-at-trivago-part-1-structure-and-itcss-52f63ed557ca)
- [CSS at Trivago 2 ](https://medium.com/@pistenprinz/css-at-trivago-part-2-naming-conventions-and-methodologies-d51b445a3a39)

**Stylelint**
- We're using `stylelint-config-standard` and `stylelint-config-property-sort-order-smacss`. Study if there's more config that can helps us with BEM or ITCSS.

Any thoughts @piensaenpixel ?

**Comment by piensaenpixel** [comment]
<3

**Comment by ivanmalagon** [comment]
Two articles to be inspired by:

https://zellwk.com/blog/css-architecture-3/

https://speakerdeck.com/dafed/managing-css-projects-with-itcss?slide=54
