### ISSUE TITLE
Positioning v1

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#39]
Another thing to take into account in Airship is positioning elements.

In [this document](https://docs.google.com/document/d/13ySuYGnZln4C81ss7RQJBBSDDrZ2xU4ym3qXaVwyofo/edit?usp=sharing) there are a collection of screenshots of custom applications. As you can see, there are no so many different patterns so special position styles won't be needed for all elements. Most elements are just block ones. We don't need a complex grid system like in Bootstrap, for instance.

### General guidelines

**Remember the grid**
In Airship we follow a visual grid system of multiples of 4px.

**Keep it simple**
As stated above, there's no need for a complex grid system (apparently). Most of the elements won't need a special treatment for positioning.

In a first look, a simple positioning system based on flexbox is enough. It's usual in Carto to offer a series of utility functions for this kind of work.

I'm thinking on something like

```html
<div class="as-row">
    <div> // All this content will go the left
        <div ...>
    </div>
    <div>..</div> // This content will go to the right
</div>
```

being the style

```
.as-row {
    display: flex;
    justify-content: space-between;
}
```

Something simple.

**Comment by rubenmoya** [comment]
With the `display` and `flex` utilities that we're implementing in https://github.com/CartoDB/airship/pull/193 I don't think we need this anymore, right @ivanmalagon?
