### ISSUE TITLE
Nodes of components in Vue

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#409]
This is a placeholder to enter information about how the Airship styles behave when inserted in a Vue application. As Vue doesn't have fragments as of now, a component needs to be wrapped in only one node.

For the experience of @Jesus89 this makes that some styles don't work properly and he needs to set the style for those nodes.

Check what happens for real and provide a solution that can be useful for other frameworks as well.

**Comment by Jesus89** [comment]
Yes, in `vue` files you must add a node inside the template. 

```html
<template>
  <div>
     <!-- Airship layout/components -->
  </div>
</template>
```

But the result is that your layout or components are not displayed. So you need to add the following style, for example, to don't break the airship chain:

```html
<template>
  <div style="display: flex; flex: 1">
     <!-- Airship layout/components -->
  </div>
</template>
```

**Comment by ivanmalagon** [comment]
The root problem is that a lot of our styles rely on the block being `flex` and their elements being `flexed` items.

For instance, `as-app` is `flex` and `as-content` has properties of `flex: 1; height: 100%`. When your component tree has `as-app` in one component and a child component is `as-content`, the child needs to be wrapped in a `div` that has no such properties. The style gets broken. This happens, at least, in Vue and React if you don't use fragments. But it will happen in any place depending on your structure.

This is potentially dangerous in all Airship elements that have `display: flex` and child elements. It's an extensive list:
- `as-banner`
- `as-breadcrumb`
- `as-checkbox`
- `as-app`
- `as-content`
- `as-main`
- `as-map-area`
- `as-map-panels--visible`
- `as-panel`
- `as-map-footer`
- `as-sidebar`
- `as-toolbar--actions`
- `as-flag`
- `as-menu-dropdown`
- `as-model`
- `as-radio`
- `as-tabs`

I'll test every combination of these elements to check if they need a workaround class for in-the-middle `divs`and come up with the minimum set of them.

Warnings in docs are needed also to mark this issue as solved.
