### ISSUE TITLE
Toolbar actions taking a lot of space

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#413]
### Current result

Having three nodes in a toolbar , one of them being `as-toolbar__actions`. This actions node takes all the available space in the container, pushing itself to the right

```html
  <header class="as-toolbar">
    <div class="as-toolbar__item"></div>
    <nav class="as-toolbar__actions"></nav>
    <div class="as-toolbar__item"></div>
  </header>
```

![image](https://user-images.githubusercontent.com/1078228/47086288-5bbe1780-d219-11e8-86c0-c6ec9b398d79.png)

![image](https://user-images.githubusercontent.com/1078228/47086309-67114300-d219-11e8-8119-d3c9ed5fd9b4.png)

### Expected result

`as-toolbar__actions` takes the needed space and all toolbar nodes layout as expected, as `space-between`.

![image](https://user-images.githubusercontent.com/1078228/47086516-09312b00-d21a-11e8-85d4-313ebe18ec8b.png)

**Comment by IagoLast** [comment]
how does it look on mobile?
