### ISSUE TITLE
Define release process

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/airship#453]
### Context

During development in the alpha stage we release several version with these problems:
- Components library was published in development mode: that broke the components in every browser except Chrome. We didn't catch it because we didn't test the release in other browsers.
- Icons couldn't be decoded: this was a problem introduced by us when uploading assets to S3.
- Components via NPM started breaking builds: after upgrading to Stencil 0.13, the function needed to load the components changed its location. We didn't catch the problem.

Although it was a perfect storm, this revealed that our release process is weak. We can't afford this kind of problems once we reach public status.

We have tests to check components and styles on its own, but no process to check the big picture.

### Goal

Define a process to ensure:
- The three libraries are well released and work properly.
    - Via CDN.
    - Via NPM.
    - In several browsers.

### Proposals

- We aim to do this in the most automatic way possible but if it takes a lot of time, it's better to have a simple manual process to check. Way better than that we have now (spoiler: we have nothing).
- Have simple "smoke tests": part of this issue is to define what to check but a complex dashboard with several widgets connected with a map, styles and icons seems to be a very good option.
- Have these "smoke tests" in another package, consuming the real deal: the CDN files and the NPM packages. For that, we'll need to publish canary releases and once we checked everything is OK, proceed to release the good one.
- If these smoke tests can be used also for https://github.com/CartoDB/airship/issues/456 -> two 🐦 , one stone.

### Discussion

- Is it worth having new smoke tests? Is there a risk that they are easily outdated?

### Steps

- [x] Update scripts to publish a [next/dev](https://docs.npmjs.com/cli/dist-tag#purpose) tag.
   - [x] Update lerna script
   - [x] Update CDN scripts
- [x] Create a new folder in the `packages` with a simple test commad to validate the `latest`tag.
   - [x] Create several `smoke.html` files.
   - [ ] Can we automate this process?
- [x] Create a section in the DEVELOPERS.md file with the release instructions
- [ ] Check how CHANGELOG gets modified because of this.

**Comment by ivanmalagon** [comment]
Reopening issue.

The instructions in `DEVELOPERS.md` for this release don't say much about the acceptance process. It only tells how to publish a prerelease tag.

Please outline what needs to be done in order to check that a release is OK and can be passed to a official release.

**Comment by IagoLast** [comment]
Fixed in https://github.com/CartoDB/airship/commits?author=IagoLast
