### ISSUE TITLE
Setup Linting

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/airship#46]
- [x] Configure stylelint for elements
- [x] Configure tslint for components
- [x] Configure stylelint for components
- [x] Add a lerna command `lint`
- [x] Add a lerna command `lint:fix`

**Comment by VictorVelarde** [comment]
### Lint configuration notes:

- **stylelint**: `.stylelintrc`shared by 'elements' and 'components'. Currently using same rules as in `cartodb`

**Comment by VictorVelarde** [comment]
Merged in. Some fine-tuning should be made later on...
