### ISSUE TITLE
Configure CI to upload releases

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/airship#469]
**Problem**
Our release process is "very slow" (5m) 

**Proposed solution**
Create a CI hook/integration to upload a pre-release on every merge to master.

Related to #463

**Comment by ivanmalagon** [comment]
A prerelease per merge can be a bit overkilling according to our current workflow.

Anyway, CDN uploads are blazing fast due to changes on https://github.com/CartoDB/airship/pull/544 (when it gets merged to master)
