### ISSUE TITLE
Layout containers: toolbar

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#47]
### Goal
The goal of this issue is to define exactly the behaviour of the toolbar container.

### Mockups

![image](https://user-images.githubusercontent.com/1078228/42810349-fe34a6f0-89b7-11e8-9b29-2a76dd3d2fd5.png)

**Side toolbar**

![image](https://user-images.githubusercontent.com/1078228/42812204-26981ba4-89bd-11e8-82de-35c91717e8d8.png)
**Top toolbar**

### Characteristics:
- Different positions:
    - Top
    - Right
    - Left

### Responsive
In mobile breakpoint, the iconbar will be always on top.

### Colors

Question for @CartoDB/design 

Should we use a color from the palette for the background by default? Which one? One of the branding ones?

![image](https://user-images.githubusercontent.com/1078228/42812501-2b9afd3c-89be-11e8-8a0c-c717d9467085.png)

**Comment by urbanphes** [comment]
In this example, the background color chosen was "Brand 2".

**Comment by ivanmalagon** [comment]
Done in https://github.com/CartoDB/airship/pull/88
