### ISSUE TITLE
Beta 8: histograms are not working

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/airship#471]
They worked up to Beta 6, now they render nothing when setting data

**Comment by IagoLast** [comment]
It works for me, can you give me a code snippet? are you using Airship from a CDN or compiled from NPM? Which OS/Browser?

**Comment by AbelVM** [comment]
Same as in your example, but using beta8 instead of the one used there (beta4)

https://carto.com/developers/airship/examples/#example-as-histogram-simple

**Comment by ivanmalagon** [comment]
As @IagoLast asked, what's your OS / browser?

**Comment by AbelVM** [comment]
Chrome, Ubuntu 18.10.1

Tested again within my code: 
* beta6: 
![image](https://user-images.githubusercontent.com/9017165/48356304-401e2380-e696-11e8-9f0b-26db09e43087.png)

* beta8: 
![image](https://user-images.githubusercontent.com/9017165/48356362-604de280-e696-11e8-8067-934bcae0545c.png)

Yep, that's a blank image  ¯\_(ツ)_/¯  No message in console, no axis labels. No "NO DATA" message 

DOM node outter HTML for beta8:
```html
<as-histogram-widget disable-interactivity="" heading="My widget" description="my description" class="burnrate hydrated">
  <as-widget-header no-data-message="NO DATA AVAILABLE" class="hydrated">
    <h2 class="as-widget-header__header">My widget</h2>
    <p class="as-widget-header__subheader as-body">my description</p>
  </as-widget-header>
  <div class="as-histogram-widget__wrapper as-histogram-widget__wrapper--disabled">
    <span role="tooltip" class="as-histogram-widget__tooltip"></span>
    <svg></svg>
  </div>
</as-histogram-widget>
```

**Comment by IagoLast** [comment]
still happening in beta.10 ?

**Comment by AbelVM** [comment]
hey, update the readme!!
![image](https://user-images.githubusercontent.com/9017165/48553254-59fc7800-e8db-11e8-8c4b-c84e2f6c805b.png)

...didn't realize the newer versions :(

**Comment by AbelVM** [comment]
Tested in beta.10, it's fixed! :tada:

**Comment by IagoLast** [comment]
> hey, update the readme!!

🤦‍♂️  you are right!

**Comment by AbelVM** [comment]
...but no X-axis, indeed :(

![image](https://user-images.githubusercontent.com/9017165/48553647-6fbe6d00-e8dc-11e8-97e3-1ae9c129e378.png)

**Comment by IagoLast** [comment]
@AbelVM can you open a new issue? 

Thx for the QA! 😄

**Comment by AbelVM** [comment]
:grin:
