### ISSUE TITLE
IE11 broken

### ISSUE THREAD

**Issue by IagoLast** [CartoDB/airship#477]
**What is happening?**
![ie11](https://user-images.githubusercontent.com/2657897/48264878-4eb4d280-e42b-11e8-83ce-cd604f026002.png)

...

I think we should review the global usage

- no css variables
- no sidebars
- stacked bar widget is not working at all
- histogram widget has wrong colors

**Comment by rjimenezda** [comment]
Histogram selection bars are not rendering properly either.

**Comment by rjimenezda** [comment]
Stacked bar widget is broken because of padStart, it's not supported on IE11

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

**Comment by IagoLast** [comment]
small new issues created, closing
