### ISSUE TITLE
IE11 - Stacked Bar does not render

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/airship#478]
This is due to using padStart, which is not supported.

We should change it and see if there's any more problems

**Comment by rjimenezda** [comment]
I agree that it would be nice to be able to dynamically load it. However, I don't know if the stencil people will include a polyfill for something they don't use.

@ivanmalagon should we add the polyfill ourselves to the code? Should we add documentation stating that to support IE11, you should include certain polyfills (the ones iago posted)

**Comment by IagoLast** [comment]
@rjimenezda they already have a polyfill system, I think it would be a nice feature to include a "loadPolyfills" flag or something like that, I think it worth to try
