### ISSUE TITLE
Rollback IE11 hacks

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#494]
After #493 we can rollback the several hacks we did to try to support IE11.

- [x] `initial` values were removed as part of https://github.com/CartoDB/airship/pull/491
- [x] parsing of `computedStyles` to extract colors from CSS variables. https://github.com/CartoDB/airship/pull/486/files
- [x] `padStart` polyfills https://github.com/CartoDB/airship/pull/487 (research if some other browsers need it)
- [x] IE11 histogram handles https://github.com/CartoDB/airship/pull/484
- [x] IE11 Remove javascript styles from widgets

Feel free to add whatever hack you are aware of.

Note: this is not urgent.

**Comment by rjimenezda** [comment]
The computedStyles thing is necessary for all browsers AFAIK. It's just a way of getting a real color from a CSS variable on runtime. I'm going to improve the robustness of the method because looking at it, a malformed CSS variable will throw an error.

**Comment by rjimenezda** [comment]
The Handles don't show up on Firefox either. Once again, Chrome is being a `listillo`. Width and Height are not presentational attributes and should not be set on CSS: https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/Presentation

`transform` is, though, so I'll revert that one.
