### ISSUE TITLE
Histogram Selection broken for buckets in range [0, 1]

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/airship#496]
Apparently the histogram selection does not work well when the buckets are in the range [0, 1].

The programmatic API works, but not the mouse events.

It works fine for negative numbers, or mixing negative numbers and positive ones.

**Comment by rjimenezda** [comment]
It also happens if you have middle values ([[1.5, 2.5], [2.5, 3.5]...etc]). It might be that we're rounding when we're not supposed to, or it might be something trickier.

To avoid these issues we could consider splitting the provided buckets and the buckets we use for the chart internals.

So if the user provides n values, we just create n equal buckets (distance doesn't really matter), and then we just map back to the user values when handling the selection.

The problem with this is that it makes having different x-scales different. Histograms don't necessarily need to have equal bins, but we're assuming so for simplicity's sake (bars are always rendered equal in width).

**Comment by ivanmalagon** [comment]
Shipped in v1.0.3
