### ISSUE TITLE
Histogram's X-axis not visible

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/airship#500]
As reported by @Abelvm 

On Beta10 we introduced a regression and now the Histogram's x-axis is not visible anymore.

**Comment by AbelVM** [comment]
Same behavior with stacked bar chart, indeed

**Comment by rjimenezda** [comment]
Oh yeah, forgot to mention that one

**Comment by IagoLast** [comment]
> Same behavior with stacked bar chart, indeed

Stacked bar char never had horizontal labeling is a pending feature not a bug

**Comment by rjimenezda** [comment]
I'll open a feature request for the stacked bar to keep track of it
