### ISSUE TITLE
Make S3 uploads parallel

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/airship#513]
The S3 upload is way too slow as it is. Uploading a prerelease (upload + 1 copy) takes several minutes, so an actual version will be even worse.

We should try making the file upload as parallel as possible (files, not chunks of a file). @ivanmalagon mentioned a library that does it for you, so maybe we should adapt the script to it instead of just using the sdk. Or we can make our own parallel version.

**Comment by ivanmalagon** [comment]
Done in https://github.com/CartoDB/airship/pull/544

**Comment by rjimenezda** [comment]
This hasn't been released, but yeah, it's in that PR
