### ISSUE TITLE
Padding between columns in stacked bars and histograms should be auto or configurable

### ISSUE THREAD

**Issue by AbelVM** [CartoDB/airship#519]
The space between columns is fixed 
![image](https://user-images.githubusercontent.com/9017165/48723123-192b9880-ec26-11e8-8980-3ea89d6e720e.png)
but the actual width of the columns get smaller as the number of them grows:
![image](https://user-images.githubusercontent.com/9017165/48722921-91458e80-ec25-11e8-8bd5-f8e4a40680ee.png)
If you add enough columns, the result is useless:
![image](https://user-images.githubusercontent.com/9017165/48723091-00bb7e00-ec26-11e8-8e69-e8885e28a8b1.png)
So, that padding space should adapt the same way the columns width is adapted

**Comment by rjimenezda** [comment]
Would you expect this to work automatically, or would you prefer this to be a prop you can pass?

**Comment by AbelVM** [comment]
Can I have both? A prop that gets automatically adjusted if not set.

I'd go with the automated one in most of the cases, anyway. Starting with [TBD]-bins, the gap should disappear and show a stacked-area-char-ish look.

**Comment by AbelVM** [comment]
So, going for the automatic value works for me. 

Maybe an on/off value is good enough, instead of recalculating. I mean, it's within the subpixel width once we start adding like >20 bars (depending on the total width), so why not use a (reasonable) fixed value up to a number of bars (depending on the total width once again), and then switch to 0px?

**Comment by ivanmalagon** [comment]
Shipped in v1.0.3
