### ISSUE TITLE
Time Series / Histogram categorical values support

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/airship#535]
Whenever this issue will be tackled on, the Histogram / Time Series will support numbers and dates as the delimitation for buckets.

We should also allow categorical values (CARTO VL supports categorical histograms), in case each bucket represents a category, without any regards to which bucket it is.

Some notes:

- Supporting a category instead of start / end can be achieved by pre-parsing the data, and generating a start / end for each category.
- On this case, the x-axis labeling won't make any sense. We should either hide it or try to display the category.
- The event dispatched when the selection changes is also pointless, because it would be the made-up buckets. We should consider emitting the categories instead.

**Comment by alexwcc** [comment]
Any updates on the priority of this?

**Comment by rjimenezda** [comment]
Added support for this on v2 (#564)
