### ISSUE TITLE
Category Widget defaultBarColor not working

### ISSUE THREAD

**Issue by rjimenezda** [CartoDB/airship#540]
The prop defaultBarColor of the category widget is not working anymore.

The regression was introduced on the big responsive PR: https://github.com/CartoDB/airship/pull/473

We removed it in favor of a pure CSS variable `--category-bar-color`, but this is an undocumented breaking change.

We should either:

- Restore it, which might be tricky.
- Mark the prop as deprecated and document the new way of doing it.

**Comment by Captain-Oski** [comment]
I second.
