### ISSUE TITLE
HistogramWidget property has wrong casing in HTML attribute specification

### ISSUE THREAD

**Issue by jesusbotella** [CartoDB/airship#542]
**What is happening?**
`selectedColor` property has camelCase in the HTML Attribute specification where it should be kebab casing. https://carto.com/developers/airship/reference/imported_content/catalog/#/components/histogram-widget?a=selectedcolor-string--47db99

**What should happen?**
Property should be `selected-color` in HTML attribute.

**Comment by rjimenezda** [comment]
Fixed, `selectedColor` is no longer a prop
