### ISSUE TITLE
Triage: fork Catalog to match reference style

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#543]
Airship reference is rendered by [Catalog](https://docs.catalog.style/)

It allows us to get a real good reference for a components library but it comes with its tradeoffs. It doesn't match the visual look & feel of the rest of the developers center.

The main issues are:

### Left menu

![image](https://user-images.githubusercontent.com/1078228/49457702-93921600-f7eb-11e8-9381-9b2de3e0a2f1.png)

1. The styles don't match.
2. The responsive behaviour: in Catalog, the menu hides in the mobile breakpoint and we don't have any mean to show it. In our docs, the menu shrinks but it's always visible.

### Typography

Headings don't match

![image](https://user-images.githubusercontent.com/1078228/49457969-29c63c00-f7ec-11e8-878b-b7e396947e5d.png)

### Code

![image](https://user-images.githubusercontent.com/1078228/49458060-54b09000-f7ec-11e8-9cbd-06e4d4a66cd5.png)

----

The goal of this ticket is to get a grasp of how complex is to fork Catalog to allow our modifications to match the proper style.

Catalog has some configuration to tweak some of the UI. You can check the options [here](https://github.com/interactivethings/catalog/blob/master/src/DefaultTheme.js)

The best way to do this would be to add our needs (headings, menu style, responsive behaviour) as theming options, so we can propose a PR. If accepted, we won't need any maintenance in our own fork. If not, ¯\_(ツ)_/¯ let's keep oru fork.

Just do a quick fork to check how much work will require tweaking the style and present the conclusions in this ticket.

Note: code highlighting could stay as it is. I don't see a major problem on that. The worst issue here is the left menu and its responsive behaviour.

Related issue: https://github.com/CartoDB/airship/issues/374

**Comment by ramiroaznar** [comment]
Is this a frontend or a design issue? @ivanmalagon

**Comment by ivanmalagon** [comment]
Front

**Comment by ivanmalagon** [comment]
👀
