### ISSUE TITLE
Integration guide with CARTO VL is wrong

### ISSUE THREAD

**Issue by elenatorro** [CartoDB/airship#575]
**What is happening?**

There's an issue with [this](https://carto.com/developers/airship/guides/integrating-CARTO-VL/) example. 

**What should happen?**

Last example, instead of:

```js
function updateWidgets() {
$categoryWidget.categories = viz.variables.cities.value
    .map(feature => ({
         name: feature.name,
         value: feature.pop_max,
      }))
      .sort((a, b) => b.value - a.value);
 };
```

It should be

```js
function updateWidgets() {
$categoryWidget.categories = viz.variables.cities.value
    .map(feature => ({
         name: feature.properties.name,
         value: feature.properties.pop_max,
      }))
      .sort((a, b) => b.value - a.value);
 };
```

**Comment by VictorVelarde** [comment]
Good catch @elenatorro. This was a change in VL API we made in v0.10, grouping the properties, that wasn't synchronized. I would add this example to the 'VL checklist for new releases'
