### ISSUE TITLE
Typo in bridge example code

### ISSUE THREAD

**Issue by VictorVelarde** [CartoDB/airship#581]
**What is happening?**
The code in https://carto.com/developers/airship/examples/#example-time-series-bridge present a small typo

**Extra information**
![image](https://user-images.githubusercontent.com/458196/55100272-c5442b00-50c1-11e9-86b3-acad0849139b.png)

**Comment by VictorVelarde** [comment]
I have checked it and the text is fine, so it is a dev-center issue, to be managed outside of this repo

**Comment by Jesus89** [comment]
I think this could be because these examples have 4 spaces instead of 2 spaces. I'll check that.

**Comment by VictorVelarde** [comment]
It's good to fix it in the source, but it would be great if we could:
- enforce an style in this project and/or
- make the developer-center more flexible on this.

This has now low priority though, so we should probably wait for more cases to make the effort. If they appear, let's reconsider this.
