### ISSUE TITLE
Legend component: Point size, classed

### ISSUE THREAD

**Issue by jorgesancha** [CartoDB/airship#584]
Point size, classed. Part of #157 :

![image](https://user-images.githubusercontent.com/86218/55345818-251b4700-54b1-11e9-9b2a-c36e73e97dcd.png)

Learn more here: https://docs.google.com/document/d/1fYFWV9vVRyfpDjcu30lGm7Fr5qZKoaTOaHfmqtGYfLE/edit?ts=5c9cf373

cc @makella @rjimenezda

**Comment by Lady-Aga** [comment]
With the vertical format, I have the doubt whether it is better to keep the same separation between texts or between circles.
What do you think?

![584 - Point size, classed](https://user-images.githubusercontent.com/49977486/57137268-a404e780-6daf-11e9-9fb9-351c512ff1f6.png)

**Comment by makella** [comment]
@Lady-Aga the more "natural" feeling one to me is the equal symbol spacing.  

Here is a screenshot from my cartography textbook with some of the same arrangements for you to see:

<img width="277" alt="Screen Shot 2019-05-03 at 2 33 33 PM" src="https://user-images.githubusercontent.com/1566273/57164214-a582df80-6db0-11e9-8e6a-e3960ae9b12e.png">

Two comments:
- As seen in example F, the length of the leader line varies which is what is giving the values alignment with the equal spacing between symbols
- Typically, leader lines and value labels are to the right of the symbols (I'd say this is common for all vertical arrangements whether there are leader lines or not).

If it helps, here is the link to the scanned portion of the text where the screenshot originates from:
https://drive.google.com/drive/folders/1BIaf9lR24CiG-5Iv2l0YhyycS7-SNY5B

Also, if you have any questions, feel free to reach out to me!

thanks!
