### ISSUE TITLE
Legend component: Point size, unclassed

### ISSUE THREAD

**Issue by jorgesancha** [CartoDB/airship#585]
Point size, unclassed, part of #157 :

![image](https://user-images.githubusercontent.com/86218/55345991-9eb33500-54b1-11e9-8d47-6f00cd4d669e.png)

Learn more here: https://docs.google.com/document/d/1fYFWV9vVRyfpDjcu30lGm7Fr5qZKoaTOaHfmqtGYfLE/edit?ts=5c9cf373

cc @makella @rjimenezda

**Comment by Lady-Aga** [comment]
![585 - Point size, unclassed](https://user-images.githubusercontent.com/49977486/57137435-2ab9c480-6db0-11e9-827e-41683ac9c754.png)

**Comment by makella** [comment]
@Lady-Aga in this scenario, where do you envision numerical values being placed? For example:

<img width="317" alt="Screen Shot 2019-05-03 at 7 34 06 AM" src="https://user-images.githubusercontent.com/1566273/57140802-e4e00a80-6d75-11e9-9708-acf9b4af27ee.png">
