### ISSUE TITLE
Legend component: Line size, classed

### ISSUE THREAD

**Issue by jorgesancha** [CartoDB/airship#586]
Line size, classed, part of #157 :

![image](https://user-images.githubusercontent.com/86218/55346042-c1dde480-54b1-11e9-8cec-b89d6030dcf1.png)

Learn more here: https://docs.google.com/document/d/1fYFWV9vVRyfpDjcu30lGm7Fr5qZKoaTOaHfmqtGYfLE/edit?ts=5c9cf373

cc @makella @rjimenezda

**Comment by Lady-Aga** [comment]
![586 - Line size, classed](https://user-images.githubusercontent.com/49977486/57137489-4c1ab080-6db0-11e9-89b8-f0a1eae829e9.png)

**Comment by makella** [comment]
@Lady-Aga would it be possible to see this legend with the unclassed line style? As mentioned there, we can think about showing fewer steps, while in the classed scenario (as mentioned in the classed color ticket), typically, these will have a max of 7 classes (again, with VL, it is now possible to go beyond that even though not recommended).

**Comment by makella** [comment]
saw this as an idea for horizontal
<img width="469" alt="Screen Shot 2019-05-03 at 7 38 16 AM" src="https://user-images.githubusercontent.com/1566273/57141029-7780a980-6d76-11e9-9805-c9279cc36188.png">
