### ISSUE TITLE
Legend component: Polygon color, classed (color steps)

### ISSUE THREAD

**Issue by jorgesancha** [CartoDB/airship#588]
Polygon color, classed (color steps), part of #157 :

![image](https://user-images.githubusercontent.com/86218/55346522-01f19700-54b3-11e9-8c99-7c0eab9052ed.png)

Learn more here: https://docs.google.com/document/d/1fYFWV9vVRyfpDjcu30lGm7Fr5qZKoaTOaHfmqtGYfLE/edit?ts=5c9cf373

cc @makella @rjimenezda

**Comment by Lady-Aga** [comment]
Should it have an initial and final value? I've done it as the example on [#157](https://github.com/CartoDB/airship/issues/157) but it might need those values...

![image](https://user-images.githubusercontent.com/49977486/57137784-2b9f2600-6db1-11e9-8d53-b2a7894e7f3c.png)


![588 - Polygon color, classed (color steps)](https://user-images.githubusercontent.com/49977486/57137626-b6335580-6db0-11e9-82c3-c49c9a046a9e.png)

**Comment by makella** [comment]
@Lady-Aga nice! can we see this with 7 class breaks? Typically, that will be the maximum (although with VL, ppl can choose as many breaks as they want). For these classed legends, I'd say the minimum would be 2 (more likely 3) and the maximum will be 7. According to CARTOColor schemes, we have sequential and diverging color schemes for: 2,3,4,5,6 and 7 classes.

**Comment by makella** [comment]
I should mention that [diverging color schemes]( will usually be an odd number 3,5,7...)

From our CARTOColors page:
"Diverging schemes
Highlight values above and below an interesting mid-point in quantitative data with these schemes. The middle color is assigned to the critical value with two sequential type palettes at either end assigned to values above or below."
