### ISSUE TITLE
Legend component: Polygon color, unclassed (gradient)

### ISSUE THREAD

**Issue by jorgesancha** [CartoDB/airship#589]
Polygon color, unclassed (gradient), part of #157 :

![image](https://user-images.githubusercontent.com/86218/55346671-5137c780-54b3-11e9-9c8c-0b48ec2e77fc.png)

Learn more here: https://docs.google.com/document/d/1fYFWV9vVRyfpDjcu30lGm7Fr5qZKoaTOaHfmqtGYfLE/edit?ts=5c9cf373

cc @makella @rjimenezda

**Comment by Lady-Aga** [comment]
![589 -  Polygon color, unclassed (gradient)](https://user-images.githubusercontent.com/49977486/57137827-42457d00-6db1-11e9-8d7e-26949cb774df.png)

**Comment by makella** [comment]
would this design support having more representative values (for example the mid ranges) labeled?
<img width="90" alt="Screen Shot 2019-05-03 at 7 56 55 AM" src="https://user-images.githubusercontent.com/1566273/57142169-20c89f00-6d79-11e9-8a4c-fda57c963c5c.png">

**Comment by makella** [comment]
Another thought, do you think the low to high should be consistent for either orientation? For example, horizontal, low values come from left whereas in vertical, lowest values are at the bottom. I wonder what your thoughts are on that... should we always show from low to high or vice/versa regardless of the legend's orientation?

**Comment by VictorVelarde** [comment]
Nice job @Lady-Aga !

@makella I would go for that, low at the left & bottom, high at the right & top. 

I would also consider moving the labels to the right of the bar in the vertical disposition. IMO it would be nice to keep consistency with this labels position in other legends, such as bubble map (labels to the right of the bubble)

**Comment by Lady-Aga** [comment]
Totally agree, I'm changing all the labels to the right in the vertical layout
