### ISSUE TITLE
Clicking on histogram bar does not filter data on map

### ISSUE THREAD

**Issue by makella** [CartoDB/airship#592]
**What is happening?**

the filtering action on the histogram bridge widget is a little confusing. in order to filter the data on the map you have to drag the slider bar across the range. but if you click on a histogram bar, you get the notice that there has been a selection but the map doesn't filter the data. 

**What should happen?**

Both actions should filter the data on the map

**Steps to Reproduce**

![bridge-filter](https://user-images.githubusercontent.com/1566273/55418964-0361a480-5531-11e9-87c2-dd4034862af5.gif)

**Device/Browser/Airship-Version**

MacBook/Chrome/2.0.5

**Extra information**

As discussed in #airship-help, this seems to be a bug

cc @rjimenezda

**Comment by Jesus89** [comment]
Fixed https://github.com/CartoDB/airship/pull/596
