### ISSUE TITLE
Multi-layer legend font sizes are different

### ISSUE THREAD

**Issue by makella** [CartoDB/airship#615]
**What is happening?**
In CF integration, with multi-layer helper methods, I am noticing that there is a difference in font size between the two layers legend labels.

in this case the range values (`color_bins_layer`):
<img width="348" alt="Screen Shot 2019-06-11 at 10 15 27 AM" src="https://user-images.githubusercontent.com/1566273/59292530-86daf880-8c3a-11e9-882a-b82c2b52c1f4.png">

in this case bins + category:
<img width="465" alt="Screen Shot 2019-06-11 at 11 21 34 AM" src="https://user-images.githubusercontent.com/1566273/59292902-36b06600-8c3b-11e9-8d55-7d56926a35f2.png">

In both cases, it looks like the top legend's labels are larger than the bottom layer's legend.

**What should happen?**
Both should be equal.

**Steps to Reproduce**
Create a multi-layer map with helper methods in CF. 

cc @rjimenezda

**Comment by rjimenezda** [comment]
Fixed in #614

Released in 2.1.0
