### ISSUE TITLE
circle distorted in size bins point legend

### ISSUE THREAD

**Issue by makella** [CartoDB/airship#617]
**What is happening?**
It looks like some of the circles on the size bins point legend are distorted.. for example, the last bin here:
<img width="179" alt="Screen Shot 2019-06-12 at 2 25 23 PM" src="https://user-images.githubusercontent.com/1566273/59383853-10afc200-8d1e-11e9-960f-3125bd6d21ee.png">

**Comment by rjimenezda** [comment]
Fixed via #623, released in 2.1.0
