### ISSUE TITLE
Infowindow reference is broken

### ISSUE THREAD

**Issue by ramiroaznar** [CartoDB/airship#637]
**What is happening?**

Only the final output is shown. The code snippets are missing. Errors are being shown in the console.

![infowindows](https://user-images.githubusercontent.com/5215798/60978999-3dadbf80-a332-11e9-9dd2-b0e5c55bf277.png)

**What should happen?**

No errors shown, snippets should be displayed.

**Steps to Reproduce**

* Go to https://carto.com/developers/airship/reference/#/components/info-window

**Device/Browser/Airship-Version**

Google Chrome 75, Ubuntu 18

**Extra information**
...

**Comment by ramiroaznar** [comment]
Oh, now I see the `<>`. Sorry!

**Comment by jesusbotella** [comment]
Sorry! I didn't put any message when closing the issue 😓 

Snippets are not displayed by default in this component, and the errors don't show up anymore, so I thought it was time to close it :)
