### ISSUE TITLE
Animation widget initial state gives wrong feeling

### ISSUE THREAD

**Issue by cmongut** [CartoDB/airship#655]
**What is happening?**
When the animation widget is loading the data it says "No data available", giving the feeling that something wrong has happened when it's not true.

![airship_initial_state](https://user-images.githubusercontent.com/711025/65956730-58806380-e44b-11e9-8285-a6480c00980a.gif)

**What should happen?**
It should give the feeling that the widget is loading the data.

**Steps to Reproduce**
We can see it when running the following CARTOframes example: https://github.com/CartoDB/cartoframes/blob/develop/examples/06_advanced/visualize-temperatures.ipynb

cc @CartoDB/rt-managers

**Comment by cmongut** [comment]
We'd like to prioritize this ticket for the CARTOframes release and also because we are starting to show CARTOframes maps in blog posts. Thank you 😇 

cc @rt-managers

**Comment by kukukaka** [comment]
FYI, @Rovaro @urbanphes

**Comment by urbanphes** [comment]
@cmongut On Builder when we had a widget (e.g. histogram) on the loading state, it would appear a border-top blue with an animation from the left to right side and also a grey boxes that are simulated the histogram blocks. 

This is an example:

![image](https://user-images.githubusercontent.com/14546701/70924251-7d877a00-2029-11ea-8b2d-e159d1da617d.png)

In this way, the users knew that the information was being loaded in that block.

To test this, on any Builder map is appreciated when this is loaded:
E.g. https://team.carto.com/u/urbanphes/builder/74dff673-ee41-4747-920c-74cf46983799/embed

<hr>

For CARTOframes we can use the same idea, and test it.

**Comment by cmongut** [comment]
Love it!

**Comment by alejandraarri** [comment]
I guess the idea is to generate loading states for all Airship widgets, right? The placeholders that are in both Dashboard and Builder widgets are HTML and CSS code and the same would be done for Airship. Keep in mind that this will take some development time, although it is not a problem to finish it for the release.

Another option is to include a generic loading state that can be applied to all widgets. In that case, the design team would have to specify how it would look like. 

@cmongut, what solution do you prefer to develop?

**Comment by cmongut** [comment]
@aleja thank you very much for the insights. It's really lovable to add suggestions about giving the same value to users with easier solutions. :top:

I would go for the loading state option. I think there is already a loading icon somewhere but I agree the design team should provide the way to go. Something like a text + the loading icon could work: "Loading data..." + the loading icon

@urbanphes, what do you think? Can we provide a loading state easier to develop?

**Comment by urbanphes** [comment]
Hey @cmongut and @alejandraarri 

I've some comments before  start to create something new:

1. As a first option and if it's possible to develop on time, I would try to make this loading states as we have on Builder. This way we have the same patterns for the loading states in our products.

2. As the 2nd option, if we couldn't develop, I would try to replicate the same design that we have but with less development. For instance, using a gif simulated the blue top bar.

What do you think?

**Comment by cmongut** [comment]
I would test option 2 to see if it's enough to understand that the component is in a loading state.

**Comment by jesusbotella** [comment]
Hi!

I can set the animated blue top bar, but what about the content placeholder? I guess that if we put the blue bar, but the content still says that `NO DATA AVAILABLE` wouldn't make sense.

Do you want me to try and develop the placeholder bars? Or anything simpler?

**Comment by urbanphes** [comment]
Hey!

@cmongut as a first part, the message NO DATA AVAILABLE  it shouldn't appear. We try to show a loading state and that message is confused to the users.

@jesusbotella it could be possible to use an image for the placeholder bars? In that case, I can proportionate the image.

**Comment by cmongut** [comment]
@urbanphes the issue is that there are different widgets that show the same strange message. If it's possible to show an image as a placeholder, we should provide three of them:

- Category widget

![image](https://user-images.githubusercontent.com/711025/72345061-10700e80-36d3-11ea-8f84-a44c796dae84.png)

- Histogram widget

![image](https://user-images.githubusercontent.com/711025/72345097-22ea4800-36d3-11ea-924c-487b012e818b.png)

- Time series widget

![image](https://user-images.githubusercontent.com/711025/72345126-34cbeb00-36d3-11ea-83ff-4177919d0108.png)

**Comment by urbanphes** [comment]
Hey, @cmongut instead make 3 cases, I would do only 2: Histogram and Category. 

I’ve prepared in a sketch document the mockups taken into account the possible backgrounds.

![Slice](https://user-images.githubusercontent.com/14546701/72348141-fbe34480-36d9-11ea-9aeb-00934a993b08.png)

@jesusbotella this is the [file](https://www.dropbox.com/s/ao2jj261y4z64u9/655%20Animation%20widget%20initial%20state%20gives%20wrong%20feeling.sketch?dl=0), and if you need something tell me.

**Comment by cmongut** [comment]
Nice alternative :)

Let's use the histogram placeholder for histogram and time-series widgets.

**Comment by jesusbotella** [comment]
@urbanphes that looks really good! Thank you

**Comment by jesusbotella** [comment]
We've just released this.

Here's how it looks:
![categorywidget](https://user-images.githubusercontent.com/4319728/72733851-fc2b8600-3b98-11ea-8c47-6285ace6aca5.gif)

![histogramwidget](https://user-images.githubusercontent.com/4319728/72733855-fdf54980-3b98-11ea-91eb-3361d0addccd.gif)

**Comment by cmongut** [comment]
😍

**Comment by urbanphes** [comment]
I'm sorry I couldn't see it with you, @jesusbotella. The work is amazing 👏
