### ISSUE TITLE
Allow multi-selection in category widget

### ISSUE THREAD

**Issue by cmongut** [CartoDB/airship#667]
**Problem**
As a user, I want to be able to select multiple categories to visualize them in a map so I can compare them.

![airship_multiselection](https://user-images.githubusercontent.com/711025/72171664-b968f180-33d3-11ea-99b5-b6b5a3a45006.gif)

**Proposed solution**
Replicate builder component behaviour.

![builder_multiselection](https://user-images.githubusercontent.com/711025/72175690-07362780-33dd-11ea-8420-a30856ef1b0f.gif)

**Comment by Jesus89** [comment]
Fixed in https://github.com/CartoDB/airship/pull/688, https://github.com/CartoDB/carto-vl/pull/1439. Released in CF 1.0.3
