### ISSUE TITLE
Modal

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#96]
![image](https://user-images.githubusercontent.com/1078228/43207402-5074c2da-9028-11e8-8f9d-b6d665c4e0b2.png)

We need to provide CSS for a modal window (scrim + modal container)

### Questions
- What color / opacity should apply to the scrim background? @CartoDB/design

**Comment by urbanphes** [comment]
Color: `#2C2C2C`
Opacity: 80%

Example:
![10_traffico_tiempo-real](https://user-images.githubusercontent.com/14546701/43388745-3b2fe40c-93ea-11e8-892e-4e5b3a66f869.png)
