### ISSUE TITLE
Main navigation tabs

### ISSUE THREAD

**Issue by ivanmalagon** [CartoDB/airship#99]
The solution to the responsive layout that we made (proposed by @piensaenpixel ) consists on hiding the panels and showing tabs to put them on first plane.

Our current implementation is:
![image](https://user-images.githubusercontent.com/1078228/43251004-0c7d2df0-90bf-11e8-9b2f-073fec385e80.png)
**Tabs at the top**

![image](https://user-images.githubusercontent.com/1078228/43251023-1a55b082-90bf-11e8-9e7a-9c6a6b96aaa4.png)
**Tabs at the bottom**

Our problem is that since this scenario was not considered in the first iteration of Airship, we don't have a visual clue on how to tackle them.

The existing tabs are for content:
![image](https://user-images.githubusercontent.com/1078228/43251149-775b45a8-90bf-11e8-9f54-c625fe696827.png)

But in the case of the navigation tabs we need to consider the following scenarios:
- Color combinations: as navigation tabs match the toolbar, that matches the branding colors, we need a design of main navigation tabs with the branding colors as background.
- Position: we've made possible putting the main nav tabs at the bottom. Are you OK with this? Do we need to make any change on this position, like putting the bold underline on top?

Please @CartoDB/design give us a hand!

**Comment by ivanmalagon** [comment]
Navigation tabs will be just like regular Airship tabs.

**Comment by urbanphes** [comment]
@ivanmalagon what do you think if we put on the tab you are with the color "Brand 03" (Green)

![group](https://user-images.githubusercontent.com/14546701/43884992-e9dbdacc-9bb7-11e8-9b89-3aafb7ee8abb.png)

**Comment by ivanmalagon** [comment]
Done at https://github.com/CartoDB/airship/pull/103
